### ISSUE TITLE
CSVテストデータ生成

### ISSUE THREAD

**Issue by ryutah** [TrashHands-on/hands-on01_csv#2]
苗字辞典使って名前生成してるっぽいですが、↓の名前ジェネレータ使ってランダムな名前生成してもらった方が楽じゃないですか？

http://namegen.chobitool.com/

**Comment by yoshioH** [comment]
うぉ、なんやコレ！
確かにこっちのほうが楽かも、、、！

とはいえ、10万件のデータ作るために個人サイトにリクエストを2,000回投げるのは申し訳ないなぁ。

**Comment by ryutah** [comment]
あー確かに攻撃扱いされかねないww
